#!/usr/bin/env bash
# Rewrite Formula/goku.rb in korniychuk/homebrew-tap for a fresh release and push it.
# Env: TAP_DEPLOY_KEY (write deploy key of the tap repo), TAG, FORMULA_VERSION, SHA256.
set -euo pipefail

readonly TAP_REPO='git@github.com:korniychuk/homebrew-tap.git'
readonly ASSET_URL="https://github.com/korniychuk/GokuRakuJoudo/releases/download/${TAG}/goku-aarch64-apple-darwin.zip"

for var in TAP_DEPLOY_KEY TAG FORMULA_VERSION SHA256; do
  if [[ -z "${!var:-}" ]]; then
    echo "::error::bump-tap: required env ${var} is empty" >&2
    exit 1
  fi
done

key_file="$(mktemp)"
trap 'rm -f "$key_file"' EXIT
printf '%s\n' "$TAP_DEPLOY_KEY" > "$key_file"
chmod 600 "$key_file"
export GIT_SSH_COMMAND="ssh -i ${key_file} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"

tap_dir="$(mktemp -d)"
git clone --depth 1 "$TAP_REPO" "$tap_dir"
mkdir -p "$tap_dir/Formula"

cat > "$tap_dir/Formula/goku.rb" <<EOF
# Generated by korniychuk/GokuRakuJoudo .github/scripts/bump-tap.sh — do not edit by hand.
class Goku < Formula
  desc "Karabiner configurator (fork: scan_next_track/scan_previous_track + auto-synced upstream)"
  homepage "https://github.com/korniychuk/GokuRakuJoudo"
  url "${ASSET_URL}"
  version "${FORMULA_VERSION}"
  sha256 "${SHA256}"

  depends_on arch: :arm64
  depends_on "joker"
  depends_on "watchexec"

  def install
    bin.install "goku"
    bin.install "gokuw"
  end

  service do
    run opt_bin/"gokuw"
    environment_variables PATH: std_service_path_env
    keep_alive true
    run_at_load true
    log_path "#{Dir.home}/Library/Logs/goku.log"
    error_log_path "#{Dir.home}/Library/Logs/goku.log"
  end

  test do
    assert_predicate bin/"goku", :executable?
  end
end
EOF

cd "$tap_dir"
git config user.name 'goku-fork-bot'
git config user.email 'goku-fork-bot@users.noreply.github.com'
git add Formula/goku.rb
if git diff --cached --quiet; then
  echo "::warning::bump-tap: formula unchanged for ${TAG} — nothing to push"
  exit 0
fi
git commit -m "goku ${FORMULA_VERSION} (${TAG})"
git push origin HEAD
